### PR TITLE
Correctly parse emojis with 19 or more character snowflakes

### PR DESCRIPTION
**Pull request by los-espaguetis**
Hey I noticed newly created emojis weren't working, I use this tool a lot and this is an easy fix for me.

### CODE REVIEW

**Comment by Glitchii** [comment]
Shouldn't emoji IDs be 18 characters in length?
Send me an example of an emoji that wouldn't work (both name and ID or Discord image link) to test it out.

**Comment by los-espaguetis** [comment]
Sorry, maybe I should have provided more context. [See here](https://www.reddit.com/r/discordapp/comments/w47zyx/fun_fact_discord_is_about_to_add_another_digit_to/).  
Here are some emojis that don't work with the current 18-char hard limit:  
<:discount:1005160487857704970>  
<:WIN:1004477424148414484>  
<:VGC:1001531532130918440>  
All 19-char snowflakes. I believe some super-old emojis might be 17 characters but don't quote me on that.

**Comment by Glitchii** [comment]
Got it.

Since Discord started from 17 numbers. The regex should perhaps be \d{17,19} or \d{17,20}, update the pull request to start from 17 or make a new one and I'll merge it.

**Comment by Glitchii** [comment]
Due to delay, this pull request will be closed and I'll update the regex in the next commit. Thank you.

**Pull request closed without merging**
